spring.application.name=greentech

# database mysql
spring.datasource.url=jdbc:mysql://localhost:3306/greentech_db
spring.datasource.username=root
spring.datasource.password=root

# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
