spring.application.name=greentech

# database H2 (salva i dati in un file cosi non si perdono quando spengo il server)
spring.datasource.url=jdbc:h2:file:./greentech_data
spring.datasource.username=sa
spring.datasource.password=

# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# console H2 per vedere i dati dal browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2
